Bills/Models/Entities/Item.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Bills.Models.Entities
{
    public class Item
    {
        public int Id { get; set; }

        [Remote(action: "ItemNameUniqe", controller: "Items", AdditionalFields = "CompanyId", ErrorMessage = "Item Name has already existed before")]
        [Required(ErrorMessage = " Item NAME is Required ")]
        [Display(Name = "Item Name : ")]
        public string Name { get; set; }

        [Range(0,int.MaxValue, ErrorMessage = "SELLING PRICE Must be Greater than or equal Zero")]
        [Required(ErrorMessage = " SellingPrice is Required, please Enter zero or more  ")]
        [Display(Name = " selling price:")]
        public int SellingPrice { get; set; }


        [Range(0, int.MaxValue, ErrorMessage = "BUYING PRICE Must be Greater than or equal Zero")]
        [Remote(action: "BuyingPriceCondition", controller: "Items", AdditionalFields = "SellingPrice", ErrorMessage = "BUYING PRICE Must be less than or equal SELLING PRICE")]
        [Display(Name = " buying Price :")]
        [Required(ErrorMessage = " buying Price  is Required, please Enter zero or more  ")]
        public int BuyingPrice { get; set; }


        public string Notes { get; set; }

        [Remote(action: "RequiredCompany", controller: "Items", ErrorMessage = "COMPANY NAME is Required")]
        [ForeignKey("CompanyData")]
        [Display(Name = "Company Name: ")]
        public int CompanyId { get; set; }


        [Remote(action: "RequiredType", controller: "Items", ErrorMessage = "TYPE NAME is Required")]
        [ForeignKey("TypeData")]
        [Display(Name = "Type Name: ")]
        public int typeId { get; set; }

    
        [Remote(action: "RequiredUnit", controller: "Items", ErrorMessage = " Unit NAME is Required")]
        [ForeignKey("Unit")]
        [Display(Name = "Unit: ")]
        public int unitId { get; set; }

        [Required(ErrorMessage = " Balance of the first duration is Required ")]
        [Display(Name = "Balance Of The First Duration ")]
        [Range(1, int.MaxValue, ErrorMessage = "Balance of the first duration Must be Greater than Zero")]
        public int BalanceOfTheFirstDuration { get; set; }

        [JsonIgnore]
        public virtual CompanyData CompanyData { get; set; }
        [JsonIgnore]
        public virtual TypeData TypeData { get; set; }
        [JsonIgnore]
        public virtual Unit Unit { get; set; }
        
        public int QuantityRest { get; set; }
        [JsonIgnore]
        public DateTime EntryDate { get; set; }



    }
}

Bills/Models/ModelView/ItemReportViewModel.cs
namespace Bills.Models.ModelView
{
    public class ItemReportViewModel
    {
        public string name { set; get; }
        public int total { set; get; }
        public int instock { set; get; }
        public int Sold { set; get; }

    }
}

Bills/Controllers/API/ItemsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bills.Models.Entities;
using Bills.Services.Interfaces;
using Bills.Models.ModelView;

namespace Bills.Controllers.API
{
    [Route("api/Items/[action]")]
    [ApiController]
    public class ItemsController : ControllerBase
    {
 
        private readonly IItemService _itemService;
        public readonly ApiModel _apiModel;

        public ItemsController( IItemService itemService, ApiModel apiModel)
        {
            _apiModel = apiModel;
            _itemService = itemService;
        }

        public IActionResult Item()
        {
            _apiModel.Data = _itemService.getAll();
            _apiModel.Success = true;
            return Ok(_apiModel);
        }

        [HttpGet("{id}")]
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 200)]
        public IActionResult Item(int id)
        {
          Item item  = _itemService.getById(id);
            if (item == null)
            {
                _apiModel.Data = null;
                _apiModel.Success = false;
                _apiModel.Message = "no found any item for this ID ";
                return NotFound(_apiModel);
            }
            else
            {
                _apiModel.Data = item;
                _apiModel.Success = true;
                return Ok(_apiModel);
            }
        }

        [HttpPost]
       
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 201)]
        public IActionResult Item(Item item)
        {
            if (ModelState.IsValid)
            {
                if (!_itemService.Unique(item.Name))
                {
                    _apiModel.Success = false;
                    _apiModel.Message = "this Item already exist ";
                    _apiModel.Data = null;
                    return BadRequest(_apiModel);
                }
                else
                {
                    item.Id = 0;
                    item.QuantityRest = item.BalanceOfTheFirstDuration;
                    _apiModel.Success = true;
                    _apiModel.Data = _itemService.create(item);
                    return Ok(_apiModel);
                }


            }
            _apiModel.Success = false;
            _apiModel.Message = "validation error ";
            _apiModel.Data = null;
            return BadRequest(_apiModel);
        }






    }
}

Bills/Controllers/ItemReportController.cs
using Bills.Models.Entities;
using Bills.Models.ModelView;
using Bills.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Bills.Controllers
{
    public class ItemReportController : Controller
    {
       
        private readonly IItemService _itemService;
        private readonly IBillItemService _billItemService;

        public ItemReportController(IBillItemService billItemService, IItemService itemService)
        {
            _billItemService = billItemService;
            _itemService = itemService;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View("searchItem" ,_itemService.getAll().Take(10).ToList());
        }

        public IActionResult Search(string search) {
            if (search == string.Empty || search==null)
            { return PartialView("_Items", _itemService.getAll().Take(10).ToList()); }
            List<Item> items = _itemService.search(search);
              return PartialView("_Items", items);
        }
        
      public IActionResult ItemDetails(int id=1)
        {
            ViewData["itemData"] = _itemService.getById(id); 
           return View("ItemDetails", _billItemService.MoreDetails(id));
        }
        public IActionResult ItemsInventory()
        {
            List<ItemReportViewModel> items = _itemService.getAll().Select(x => new ItemReportViewModel()
            {
                name = x.Name,
                total = x.BalanceOfTheFirstDuration,
                instock = x.QuantityRest
            }).ToList();
            return View("ItemsInventory", items);
        }
        [HttpGet]
        public JsonResult PopulationChart()
        {
            var populationList = _itemService.getAll().Select(x => new ItemReportViewModel()
            {
                name = x.Name,
                total = x.BalanceOfTheFirstDuration,
                instock = x.QuantityRest
            }).ToList();
            return Json(populationList);
        }
    }
}

Bills/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bills.Models;
using Bills.Models.Entities;
using Bills.Services.Interfaces;

namespace Bills.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ITypeDataService _typeDataService;
        private readonly IUnitService _unitService;
        private readonly IItemService _itemService;

        public ItemsController(ICompanyService companyService, ITypeDataService typeDataService, IUnitService unitService , IItemService itemService)
        {
            _companyService = companyService;
            _typeDataService = typeDataService;
            _unitService = unitService;
            _itemService = itemService;
        }



        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_companyService.getAll(), "Id", "Name");
            ViewData["typeId"] = new SelectList(_typeDataService.getAll(), "Id", "Name");
            ViewData["unitId"] = new SelectList(_unitService.getAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( Item item)
        {
            if (ModelState.IsValid)
            {
                    item.QuantityRest = item.BalanceOfTheFirstDuration;
                    item.EntryDate = DateTime.Now;
                   _itemService.create(item);
                    return RedirectToAction("Create", "Clients");
            }
            ViewData["CompanyId"] = new SelectList(_companyService.getAll(), "Id", "Name");
            ViewData["typeId"] = new SelectList(_typeDataService.getAll(), "Id", "Name");
            ViewData["unitId"] = new SelectList(_unitService.getAll(), "Id", "Name");
            return View(item);
        }
        public IActionResult ItemNameUniqe(string Name )
        {

            return Json(_itemService.Unique(Name));

        }

        #region AJAX method
        public IActionResult UpdateSelector(int id ) {
            List<TypeData> typeDatas = _typeDataService.getByCompanyId(id);
            return Json(typeDatas);
        }
        #endregion

        #region remot method
        public IActionResult BuyingPriceCondition(int BuyingPrice, int SellingPrice)
        {
            if (BuyingPrice <= SellingPrice)
            {

                return Json(true);

            }
            else
            {
                return Json(false);
            }

        }
        public IActionResult RequiredCompany(int CompanyId)
        {
            if (CompanyId <= 0)
            {

                return Json(false);

            }
            else
            {
                return Json(true);
            }

        }
        public IActionResult RequiredType(int typeId)
        {
            if (typeId <= 0)
            {

                return Json(false);

            }
            else
            {
                return Json(true);
            }

        }
        public IActionResult RequiredUnit(int unitId)
        {
            if (unitId <= 0)
            {

                return Json(false);

            }
            else
            {
                return Json(true);
            }

        }
        #endregion
    }
}

Bills/Views/ItemReport/ItemDetails.cshtml
@model List<BillItem>
<section id="horizontal-form-layouts">

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="card-title-wrap bar-success">
						<h4 class="card-title" id="horz-layout-basic"> Item name : @ViewBag.itemData.Name </h4>
					</div>
					<p class="mb-0">This is the basic horizontal form with labels on left and cost estimation form is the default position.</p>
				</div>
				<div class="card-body">
					<div class="px-3">
					 <div class="row">
                         
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title-wrap bar-success">
                                                <h4 class="form-section" style="    line-height: 3rem;    margin-bottom: .5rem;">
                                                      <i class="icon-layers"></i> Items </h4>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="px-3">
                                         <table class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr style="text-align: center;" >
                                                                <th>Bill Number </th>
                                                                <th>Bill date</th>
                                                                <th>Clint Name</th>
                                                                <th>Selling Price</th>
                                                                <th>Quantity</th>
                                                             
                                                              

                                                            </tr>
                                                        </thead>
                                                
                                                        <tbody id="tableItem">
                                                             
                                                                
                                                                  @if (@Model!= null)
                                                                 {
                                                                      @foreach (BillItem item in Model )
                                                                        {
	                                                                        <tr>

		                                                                        <td>@item.bill.Id    </td >
                                                                                <td>@item.bill.BillDate </td >
                                                                                <td>@item.bill.client.Name    </td >
		                                                                        <td>@item.SellingPrice   </td >
                                                                                <td>@item.Quantity   </td >
                                                                                
                                                                            </tr>
                                                              
                                                                        }
                                                                     
                                                                 }
                                                             
                                                           
	                                                       
                                                        </tbody>
                                         
                                                       
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

   </div>



				</div>

			</div>
		</div>
	</div>
</section>

Bills/Views/ItemReport/ItemsInventory.cshtml
@model List<ItemReportViewModel>
@{
    ViewData["Title"] = "ItemsReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section id="horizontal-form-layouts">

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="card-title-wrap bar-success">
						<h4 class="card-title" id="horz-layout-basic">Items inventory </h4>
					</div>
					<p class="mb-0">This is the basic horizontal form with labels on left and cost estimation form is the default position.</p>
				</div>
				<div class="card-body">
					<div class="px-3">
					 <div class="row">
                         
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title-wrap bar-success">
                                               <h4 class="form-section" style="    line-height: 3rem;    margin-bottom: .5rem;">
                                                      <i class="icon-layers"></i> Items </h4>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="px-3">
                               <table class="table table-stripped table-hover "> <thead>
                                                <tr>
                                                    <th>Name </th>
                                                    <th>Total </th>
                                                    <th>in stock</th>
                                                     <th>sold</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            @foreach (var item in Model)
                                            {
                                                 if (item.instock == 0) { 
                                                            <tr class="table-danger"> <td>@item.name </td> <td>@item.total</td><td>@item.instock</td> <td>@(item.total-item.instock)</td></tr>
                                                        } else if (item.instock==item.total)
                                                        {
                                                             <tr class="table-warning"> <td>@item.name </td> <td>@item.total</td><td>@item.instock</td> <td>@(item.total-item.instock)</td></tr>
                                                        } else
                                                        {
                                                            
                                                      
                                                        <tr> <td>@item.name </td> <td>@item.total</td><td>@item.instock</td> <td>@(item.total-item.instock)</td></tr>
                                            
                                                          }
                                                          }
                                            </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

   </div>



				</div>

			</div>
		</div>
	</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>

        $(document).ready(function () {

            $.ajax({
                type: 'GET',
                dataType: "json",
                contentType: "application/json",
                url: '/ItemReport/PopulationChart',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });

            function drawChart(result) {

                var data = new google.visualization.DataTable();
                data.addColumn('string', 'name');
                data.addColumn('number', 'Quantity');
                data.addColumn('number', 'Instock');
                var dataArray = [];
                $.each(result, function (i, obj) {
                    dataArray.push([obj.name, obj.total,obj.instock]);
                });

                data.addRows(dataArray);

                var piechart_options = {
                    title: 'items percentages ',
                    width: 400,
                    height: 300
                };
                var piechart = new google.visualization.PieChart(document
                    .getElementById('piechart_div'));
                piechart.draw(data, piechart_options);

                var barchart_options = {
                    title: 'total quantity and instock',
                    width: 400,
                    height: 300,
                    legend: 'none'
                };
                var barchart = new google.visualization.BarChart(document
                    .getElementById('barchart_div'));
                barchart.draw(data, barchart_options);
            }


        });

    </script>


    <h3> Chart </h3>
    <table class="columns">
        <tr>
           @* <td><div id="piechart_div" style="border: 1px solid #ccc"></div></td>*@
            <td><div id="barchart_div" style="border: 1px solid #ccc"></div></td>
        </tr>
    </table>

Bills/Views/ItemReport/_Items.cshtml
@model List<Item> 

    @if (@Model!=null)
           { 
               @foreach (Item item in Model )
                    {
	                    <tr>

		                    <td>@item.Name    </td >
                            <td>@item.EntryDate </td >
                            <td>@item.CompanyData.Name     </td >
		                    <td>@item.TypeData.Name    </td >
                            <td> <form asp-action="ItemDetails" asp-controller="ItemReport" >
                                <input name="id" value=@item.Id hidden>
                                 <button class="btn btn-success"  type="submit"> more Details </button>
                            </form>
                            </td>
                        </tr>
                                                              
                    }
           }
                      

Bills/Views/ItemReport/searchItem.cshtml
@model List<Item> 
<section id="horizontal-form-layouts">

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="card-title-wrap bar-success">
						<h4 class="card-title" id="horz-layout-basic">Items	 Report </h4>
					</div>
					<p class="mb-0">This is the basic horizontal form with labels on left and cost estimation form is the default position.</p>
				</div>
				<div class="card-body">
					<div class="px-3">
						
							<div class="form-group row">
								<label class="col-md-2 h4 label-control" style="font-weight: bolder" for="search"> Search :</label>
								<div class="col-md-10">
									<input name="search" class="form-control" id="search" onkeyup="getItems(this)">
									<span name="search" class="text-danger" id="searchSpan"></span>
								</div>
							</div>
							
						  <div class="form-actions">
							
							</div>

			
					 <div class="row">
                         
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title-wrap bar-success">
                                               <h4 class="form-section" style="    line-height: 3rem;    margin-bottom: .5rem;">
                                                      <i class="icon-layers"></i> Items </h4>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="px-3">
                                         <table class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr style="text-align: center;" >
                                                                <th>Item Name</th>
                                                                <th>entry date</th>
                                                                <th>Company's name</th>
                                                                <th>type name</th>
                                                                <th>More Info</th>
                                                             
                                                              

                                                            </tr>
                                                        </thead>
                                                
                                                        <tbody id="tableItem">
                                                            @if (@Model!=null)
                                                           {
                                                                <partial name="_Items" model="@Model" ></partial>
                                                           }
                                                           
	                                                       
                                                        </tbody>
                                         
                                                       
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

   </div>



				</div>

			</div>
		</div>
	</div>
</section>






	<script>

	
        function getItems(el){
			let search = el.value;

              $.ajax({
            url: "/ItemReport/Search",
            data:{"search":search,},
           // dataType: 'json',
            contentType: "application/json; charset=utf-8",
            success: function(result){
             $("#tableItem").html(result);
            },
                failure: function (response) {
                    alert(response.responseText);
                    console.log(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                    console.log(response.responseText);
                }
         
     
     });
	 }

	</script>