Bills/Models/Entities/TypeData.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Bills.Models.Entities
{
    public class TypeData
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Notes { get; set; }


        [JsonIgnore]
        public virtual ICollection<CompanyType> CompanyTypes { get; set; }

    }
}

Bills/Controllers/API/TypeDatasController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Bills.Models.Entities;
using Bills.Models.ModelView;
using Bills.Services.Interfaces;

namespace Bills.Controllers.API
{
    [Route("api/TypeData/[action]")]
    [ApiController]
    public class TypeDatasController : ControllerBase
    {
    
        private readonly ITypeDataService _typeDataService;
        public readonly ApiModel _apiModel;

        public TypeDatasController(ITypeDataService typeDataService, ApiModel apiModel)
        {
            
            _typeDataService = typeDataService;
            _apiModel = apiModel;
        }

        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 200)]
        public IActionResult Type()
        {
            _apiModel.Data = _typeDataService.getAll();
            _apiModel.Success = true;
            return Ok(_apiModel);
        }

        [HttpGet("{id}")]
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 200)]
        public IActionResult Type(int id)
        {
            TypeData typeData = _typeDataService.getById(id);
            if (typeData == null)
            {
                _apiModel.Data = null;
                _apiModel.Success = false;
                _apiModel.Message = "this Id not found ";
                return NotFound(_apiModel);
            }
            else
            {
                _apiModel.Data = typeData;
                _apiModel.Success = true;
                return Ok(_apiModel);
            }
        }
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 200)]
        public IActionResult TypesByCompanyId(int id)
        {
            List<TypeData> typeData = _typeDataService.getByCompanyId(id);
            if (typeData == null)
            {
                _apiModel.Data = null;
                _apiModel.Success = false;
                _apiModel.Message = "no types for this company ";
                return NotFound(_apiModel);
            }
            else
            {
                _apiModel.Data = typeData;
                _apiModel.Success = true;
                return Ok(_apiModel);
            }
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(typeof(IEnumerable<ApiModel>), 201)]
        public IActionResult Type(TypeView typeView)
        {
            if (ModelState.IsValid)
            {
                if (typeView.CompanyId == 0)
                {
                    _apiModel.Success=false;
                    _apiModel.Message = "COMPANY NAME is Required";
                    _apiModel.Data=null;
                    return BadRequest(_apiModel);
                }
                else
                {

                    _apiModel.Success = true;
                    _apiModel.Message = " ";
                    _apiModel.Data = _typeDataService.create(typeView); 
                    return Ok(_apiModel);
                }
            }
            _apiModel.Success = false;
            _apiModel.Message = "validation error ";
            _apiModel.Data = null;
            return BadRequest(_apiModel);
        }

       



    }
}

Bills/Controllers/TypeDatasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bills.Models.ModelView;
using Bills.Services.Interfaces;

namespace Bills.Controllers
{
    public class TypeDatasController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ITypeDataService _typeDataService;

        public TypeDatasController(ICompanyService companyService, ITypeDataService typeDataService)
        {
            _companyService = companyService;
            _typeDataService = typeDataService;
        }

      
        public IActionResult Create()
        {
            SelectList companysList = new (_companyService.getAll(), "Id", "Name");
            ViewData["companys"]= companysList;
            return View(new TypeView());
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TypeView typeView)
        {
            if (ModelState.IsValid)
            {
                _typeDataService.create(typeView);
                return RedirectToAction("Create", "Units");
              
            }
            SelectList companysList = new (_companyService.getAll(), "Id", "Name");
            ViewData["companys"] = companysList;
            return View(typeView);
        }

        public IActionResult TypeNameUniqe(string Name ,int  CompanyId) {
            return Json(_typeDataService.Unique(Name,CompanyId));
        }



    }
}

Bills/Views/TypeDatas/Create.cshtml
@model Bills.Models.ModelView.TypeView

@{
    ViewData["Title"] = "Create";
}

      <section id="horizontal-form-layouts">
                   
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title-wrap bar-success">
                                            <h4 class="card-title" id="horz-layout-basic">Company Data Form</h4>
                                        </div>
                                        <p class="mb-0">This is the basic horizontal form with labels on left and cost estimation form is the default position.</p>
                                    </div>
                                    <div class="card-body">
                                        <div class="px-3">
                                            <form class="form form-horizontal" asp-action="Create" asp-controller="TypeDatas" method="post"  >
                                                 <div class="form-group row" style="align-items: baseline;">
                                                     <label asp-for="CompanyId" class="col-md-3 label-control"></label>
                                                    <div class="col-md-9">
                                                       @if (ViewBag.companys!= null)
                                                           {
                                                                <select class="form-control mt-2" asp-for="CompanyId"  asp-items="ViewBag.companys"  >
                                                                         <option value="0" selected >Select Company</option>
                                                                </select>
                                                                   <span asp-validation-for="CompanyId" class="text-danger"></span>
                                                               
                                                           }
                                                         
                                                    </div>
                                                </div>
                                           
                                                <div class="form-group row">
                                                        <label asp-for="Name" class="col-md-3 label-control"></label>
                                                    <div class="col-md-9">
                                                        <input asp-for="Name" class="form-control" />
                                                            <span asp-validation-for="Name" class="text-danger"></span>
                                                    </div>
                                                 </div>

                                                    <div class="form-group row">
                                                         <label asp-for="Notes" class="col-md-3 label-control"></label>
                                                         <div class="col-md-9">
                                                            <textarea  asp-for="Notes" rows="5" class="form-control" ></textarea>
															 <span asp-validation-for="Notes" class="text-danger"></span>
                                                        </div>
                                                    </div>
													<div class="form-actions" style="border-top:none">
														<a asp-action="Index" asp-controller="Home" class="btn btn-danger mr-1">
															<i class="icon-trash"></i> Cancel
														</a>
														<button class="btn btn-success"  type="submit">
															<i class="icon-note"></i> Save
														</button>
													
													</div>

                                                </form>
                                                </div>
                    
                                                </div>
                                            
                                        </div>
                                    
                                </div>
                            </div>
                        </section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}